### ISSUE TITLE
If bee_workdir does not exist a workflow submitted using directory path does not work

### ISSUE THREAD

**Issue by pagrubel** [lanl/BEE#617]
Although we make the bee_workdir when submitting a workflow from a directory, packaging a workflow uses the archives subdirectory which does not exist and an error occurs. The workaround is to mkdir the archives directory.

```
 beeclient submit clamr beeflow/data/cwl/bee_workflows/clamr-wf clamr_wf.cwl clamr_job.yml .
Detected directory instead of packaged workflow. Packaging Directory...
Traceback (most recent call last):
  File "/projects/opt/centos8/x86_64/miniconda3/py39_4.12.0/lib/python3.9/shutil.py", line 823, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/vast/home/pagrubel/BEE/BEE/clamr-wf.tgz' -> '/vast/home/pagrubel/.beeflow/archives/clamr-wf.tgz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/vast/home/pagrubel/.cache/pypoetry/virtualenvs/hpc-beeflow-YDRVf3zF-py3.9/bin/beeclient", line 5, in <module>
    main()
  File "/vast/home/pagrubel/BEE/BEE/beeflow/client/bee_client.py", line 438, in main
    app()
  File "/vast/home/pagrubel/.cache/pypoetry/virtualenvs/hpc-beeflow-YDRVf3zF-py3.9/lib/python3.9/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/vast/home/pagrubel/.cache/pypoetry/virtualenvs/hpc-beeflow-YDRVf3zF-py3.9/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/vast/home/pagrubel/.cache/pypoetry/virtualenvs/hpc-beeflow-YDRVf3zF-py3.9/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/vast/home/pagrubel/.cache/pypoetry/virtualenvs/hpc-beeflow-YDRVf3zF-py3.9/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/vast/home/pagrubel/.cache/pypoetry/virtualenvs/hpc-beeflow-YDRVf3zF-py3.9/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/vast/home/pagrubel/.cache/pypoetry/virtualenvs/hpc-beeflow-YDRVf3zF-py3.9/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/vast/home/pagrubel/.cache/pypoetry/virtualenvs/hpc-beeflow-YDRVf3zF-py3.9/lib/python3.9/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "/vast/home/pagrubel/BEE/BEE/beeflow/client/bee_client.py", line 182, in submit
    package(wf_path, pathlib.Path(bee_workdir))
  File "/vast/home/pagrubel/BEE/BEE/beeflow/client/bee_client.py", line 276, in package
    shutil.move(tarball_path, package_path)
  File "/projects/opt/centos8/x86_64/miniconda3/py39_4.12.0/lib/python3.9/shutil.py", line 843, in move
    copy_function(src, real_dst)
  File "/projects/opt/centos8/x86_64/miniconda3/py39_4.12.0/lib/python3.9/shutil.py", line 444, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/projects/opt/centos8/x86_64/miniconda3/py39_4.12.0/lib/python3.9/shutil.py", line 266, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/vast/home/pagrubel/.beeflow/archives/clamr-wf.tgz'
(hpc-beeflow-YDRVf3zF-py3.9) (base) pagrubel@darwin-fe1 BEE$ llt ~/.beeflow
total 12
drwxrwxr-x 2 pagrubel pagrubel  4096 Nov 28 15:33 logs
drwxrwxr-x 2 pagrubel pagrubel  4096 Nov 28 15:33 sockets
drwxrwxr-x 2 pagrubel pagrubel  4096 Nov 28 15:33 scheduler
-rw-r--r-- 1 pagrubel pagrubel 12288 Nov 28 15:33 tm.db
(hpc-beeflow-YDRVf3zF-py3.9) (base) pagrubel@darwin-fe1 BEE$ mkdir ~/.beeflow/archives
(hpc-beeflow-YDRVf3zF-py3.9) (base) pagrubel@darwin-fe1 BEE$ beeclient submit clamr beeflow/data/cwl/bee_workflows/clamr-wf clamr_wf.cwl clamr_job.yml .
Detected directory instead of packaged workflow. Packaging Directory...
Package clamr-wf.tgz created successfully
Workflow submitted! Your workflow id is 571229.
```

**Comment by pagrubel** [comment]
To clarify, this would only happen when a user has just started using BEE or when one deletes the bee_workdir (~/.beeflow) and starts over and then submits a workflow from a directory not a tarball.

**Comment by pagrubel** [comment]
Jake pointed out that the tarball is saved here:
https://github.com/lanl/BEE/blob/develop/beeflow/client/bee_client.py#L181

maybe just leave off archives
